### ISSUE TITLE
make android issue

### ISSUE THREAD

**Issue by fredj** [Geoportail-Luxembourg/LuxMob#5]
```
...
BUILD FAILED
/opt/android-sdk/tools/ant/build.xml:597: The following error occurred while executing this line:
/home/fredj/code/LuxMob/cordova-app/platforms/android/CordovaLib/build.xml:90: Cannot find /home/pierre/local/opt/adt-bundle-linux-x86/sdk/tools/ant/build.xml imported from /home/fredj/code/LuxMob/cordova-app/platforms/android/CordovaLib/build.xml

Total time: 0 seconds

/home/fredj/code/LuxMob/cordova-app/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: ant with args: release,-f,/home/fredj/code/LuxMob/cordova-app/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /home/fredj/code/LuxMob/cordova-app/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:854:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
Makefile:21: recipe for target 'android' failed
make: *** [android] Error 1
```

many paths are absolute and starts with `/home/pierre/`

**Comment by pgiraud** [comment]
There's a (hidden) workaround in the README.  ;-)
https://github.com/Geoportail-Luxembourg/LuxMob#android

**Comment by fredj** [comment]
@pgiraud thanks for the hint, I didn't notice ...
